
/* !!! This is code generated by Prisma. Do not edit directly. !!! */
/* eslint-disable */
// @ts-nocheck 
/*
 * This file exports the `SectionImage` model and its related types.
 *
 * 🟢 You can import this file directly.
 */
import type * as runtime from "@prisma/client/runtime/library"
import type * as $Enums from "../enums"
import type * as Prisma from "../internal/prismaNamespace"

/**
 * Model SectionImage
 * 
 */
export type SectionImageModel = runtime.Types.Result.DefaultSelection<Prisma.$SectionImagePayload>

export type AggregateSectionImage = {
  _count: SectionImageCountAggregateOutputType | null
  _min: SectionImageMinAggregateOutputType | null
  _max: SectionImageMaxAggregateOutputType | null
}

export type SectionImageMinAggregateOutputType = {
  id: string | null
  url: string | null
  label: string | null
  description: string | null
  createdAt: Date | null
}

export type SectionImageMaxAggregateOutputType = {
  id: string | null
  url: string | null
  label: string | null
  description: string | null
  createdAt: Date | null
}

export type SectionImageCountAggregateOutputType = {
  id: number
  url: number
  label: number
  description: number
  tags: number
  createdAt: number
  _all: number
}


export type SectionImageMinAggregateInputType = {
  id?: true
  url?: true
  label?: true
  description?: true
  createdAt?: true
}

export type SectionImageMaxAggregateInputType = {
  id?: true
  url?: true
  label?: true
  description?: true
  createdAt?: true
}

export type SectionImageCountAggregateInputType = {
  id?: true
  url?: true
  label?: true
  description?: true
  tags?: true
  createdAt?: true
  _all?: true
}

export type SectionImageAggregateArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Filter which SectionImage to aggregate.
   */
  where?: Prisma.SectionImageWhereInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/sorting Sorting Docs}
   * 
   * Determine the order of SectionImages to fetch.
   */
  orderBy?: Prisma.SectionImageOrderByWithRelationInput | Prisma.SectionImageOrderByWithRelationInput[]
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination#cursor-based-pagination Cursor Docs}
   * 
   * Sets the start position
   */
  cursor?: Prisma.SectionImageWhereUniqueInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Take `±n` SectionImages from the position of the cursor.
   */
  take?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Skip the first `n` SectionImages.
   */
  skip?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/aggregations Aggregation Docs}
   * 
   * Count returned SectionImages
  **/
  _count?: true | SectionImageCountAggregateInputType
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/aggregations Aggregation Docs}
   * 
   * Select which fields to find the minimum value
  **/
  _min?: SectionImageMinAggregateInputType
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/aggregations Aggregation Docs}
   * 
   * Select which fields to find the maximum value
  **/
  _max?: SectionImageMaxAggregateInputType
}

export type GetSectionImageAggregateType<T extends SectionImageAggregateArgs> = {
      [P in keyof T & keyof AggregateSectionImage]: P extends '_count' | 'count'
    ? T[P] extends true
      ? number
      : Prisma.GetScalarType<T[P], AggregateSectionImage[P]>
    : Prisma.GetScalarType<T[P], AggregateSectionImage[P]>
}




export type SectionImageGroupByArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  where?: Prisma.SectionImageWhereInput
  orderBy?: Prisma.SectionImageOrderByWithAggregationInput | Prisma.SectionImageOrderByWithAggregationInput[]
  by: Prisma.SectionImageScalarFieldEnum[] | Prisma.SectionImageScalarFieldEnum
  having?: Prisma.SectionImageScalarWhereWithAggregatesInput
  take?: number
  skip?: number
  _count?: SectionImageCountAggregateInputType | true
  _min?: SectionImageMinAggregateInputType
  _max?: SectionImageMaxAggregateInputType
}

export type SectionImageGroupByOutputType = {
  id: string
  url: string
  label: string
  description: string | null
  tags: string[]
  createdAt: Date
  _count: SectionImageCountAggregateOutputType | null
  _min: SectionImageMinAggregateOutputType | null
  _max: SectionImageMaxAggregateOutputType | null
}

type GetSectionImageGroupByPayload<T extends SectionImageGroupByArgs> = Prisma.PrismaPromise<
  Array<
    Prisma.PickEnumerable<SectionImageGroupByOutputType, T['by']> &
      {
        [P in ((keyof T) & (keyof SectionImageGroupByOutputType))]: P extends '_count'
          ? T[P] extends boolean
            ? number
            : Prisma.GetScalarType<T[P], SectionImageGroupByOutputType[P]>
          : Prisma.GetScalarType<T[P], SectionImageGroupByOutputType[P]>
      }
    >
  >



export type SectionImageWhereInput = {
  AND?: Prisma.SectionImageWhereInput | Prisma.SectionImageWhereInput[]
  OR?: Prisma.SectionImageWhereInput[]
  NOT?: Prisma.SectionImageWhereInput | Prisma.SectionImageWhereInput[]
  id?: Prisma.StringFilter<"SectionImage"> | string
  url?: Prisma.StringFilter<"SectionImage"> | string
  label?: Prisma.StringFilter<"SectionImage"> | string
  description?: Prisma.StringNullableFilter<"SectionImage"> | string | null
  tags?: Prisma.StringNullableListFilter<"SectionImage">
  createdAt?: Prisma.DateTimeFilter<"SectionImage"> | Date | string
}

export type SectionImageOrderByWithRelationInput = {
  id?: Prisma.SortOrder
  url?: Prisma.SortOrder
  label?: Prisma.SortOrder
  description?: Prisma.SortOrderInput | Prisma.SortOrder
  tags?: Prisma.SortOrder
  createdAt?: Prisma.SortOrder
}

export type SectionImageWhereUniqueInput = Prisma.AtLeast<{
  id?: string
  AND?: Prisma.SectionImageWhereInput | Prisma.SectionImageWhereInput[]
  OR?: Prisma.SectionImageWhereInput[]
  NOT?: Prisma.SectionImageWhereInput | Prisma.SectionImageWhereInput[]
  url?: Prisma.StringFilter<"SectionImage"> | string
  label?: Prisma.StringFilter<"SectionImage"> | string
  description?: Prisma.StringNullableFilter<"SectionImage"> | string | null
  tags?: Prisma.StringNullableListFilter<"SectionImage">
  createdAt?: Prisma.DateTimeFilter<"SectionImage"> | Date | string
}, "id">

export type SectionImageOrderByWithAggregationInput = {
  id?: Prisma.SortOrder
  url?: Prisma.SortOrder
  label?: Prisma.SortOrder
  description?: Prisma.SortOrderInput | Prisma.SortOrder
  tags?: Prisma.SortOrder
  createdAt?: Prisma.SortOrder
  _count?: Prisma.SectionImageCountOrderByAggregateInput
  _max?: Prisma.SectionImageMaxOrderByAggregateInput
  _min?: Prisma.SectionImageMinOrderByAggregateInput
}

export type SectionImageScalarWhereWithAggregatesInput = {
  AND?: Prisma.SectionImageScalarWhereWithAggregatesInput | Prisma.SectionImageScalarWhereWithAggregatesInput[]
  OR?: Prisma.SectionImageScalarWhereWithAggregatesInput[]
  NOT?: Prisma.SectionImageScalarWhereWithAggregatesInput | Prisma.SectionImageScalarWhereWithAggregatesInput[]
  id?: Prisma.StringWithAggregatesFilter<"SectionImage"> | string
  url?: Prisma.StringWithAggregatesFilter<"SectionImage"> | string
  label?: Prisma.StringWithAggregatesFilter<"SectionImage"> | string
  description?: Prisma.StringNullableWithAggregatesFilter<"SectionImage"> | string | null
  tags?: Prisma.StringNullableListFilter<"SectionImage">
  createdAt?: Prisma.DateTimeWithAggregatesFilter<"SectionImage"> | Date | string
}

export type SectionImageCreateInput = {
  id?: string
  url: string
  label: string
  description?: string | null
  tags?: Prisma.SectionImageCreatetagsInput | string[]
  createdAt?: Date | string
}

export type SectionImageUncheckedCreateInput = {
  id?: string
  url: string
  label: string
  description?: string | null
  tags?: Prisma.SectionImageCreatetagsInput | string[]
  createdAt?: Date | string
}

export type SectionImageUpdateInput = {
  id?: Prisma.StringFieldUpdateOperationsInput | string
  url?: Prisma.StringFieldUpdateOperationsInput | string
  label?: Prisma.StringFieldUpdateOperationsInput | string
  description?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  tags?: Prisma.SectionImageUpdatetagsInput | string[]
  createdAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
}

export type SectionImageUncheckedUpdateInput = {
  id?: Prisma.StringFieldUpdateOperationsInput | string
  url?: Prisma.StringFieldUpdateOperationsInput | string
  label?: Prisma.StringFieldUpdateOperationsInput | string
  description?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  tags?: Prisma.SectionImageUpdatetagsInput | string[]
  createdAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
}

export type SectionImageCreateManyInput = {
  id?: string
  url: string
  label: string
  description?: string | null
  tags?: Prisma.SectionImageCreatetagsInput | string[]
  createdAt?: Date | string
}

export type SectionImageUpdateManyMutationInput = {
  id?: Prisma.StringFieldUpdateOperationsInput | string
  url?: Prisma.StringFieldUpdateOperationsInput | string
  label?: Prisma.StringFieldUpdateOperationsInput | string
  description?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  tags?: Prisma.SectionImageUpdatetagsInput | string[]
  createdAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
}

export type SectionImageUncheckedUpdateManyInput = {
  id?: Prisma.StringFieldUpdateOperationsInput | string
  url?: Prisma.StringFieldUpdateOperationsInput | string
  label?: Prisma.StringFieldUpdateOperationsInput | string
  description?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  tags?: Prisma.SectionImageUpdatetagsInput | string[]
  createdAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
}

export type StringNullableListFilter<$PrismaModel = never> = {
  equals?: string[] | Prisma.ListStringFieldRefInput<$PrismaModel> | null
  has?: string | Prisma.StringFieldRefInput<$PrismaModel> | null
  hasEvery?: string[] | Prisma.ListStringFieldRefInput<$PrismaModel>
  hasSome?: string[] | Prisma.ListStringFieldRefInput<$PrismaModel>
  isEmpty?: boolean
}

export type SectionImageCountOrderByAggregateInput = {
  id?: Prisma.SortOrder
  url?: Prisma.SortOrder
  label?: Prisma.SortOrder
  description?: Prisma.SortOrder
  tags?: Prisma.SortOrder
  createdAt?: Prisma.SortOrder
}

export type SectionImageMaxOrderByAggregateInput = {
  id?: Prisma.SortOrder
  url?: Prisma.SortOrder
  label?: Prisma.SortOrder
  description?: Prisma.SortOrder
  createdAt?: Prisma.SortOrder
}

export type SectionImageMinOrderByAggregateInput = {
  id?: Prisma.SortOrder
  url?: Prisma.SortOrder
  label?: Prisma.SortOrder
  description?: Prisma.SortOrder
  createdAt?: Prisma.SortOrder
}

export type SectionImageCreatetagsInput = {
  set: string[]
}

export type StringFieldUpdateOperationsInput = {
  set?: string
}

export type NullableStringFieldUpdateOperationsInput = {
  set?: string | null
}

export type SectionImageUpdatetagsInput = {
  set?: string[]
  push?: string | string[]
}

export type DateTimeFieldUpdateOperationsInput = {
  set?: Date | string
}



export type SectionImageSelect<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = runtime.Types.Extensions.GetSelect<{
  id?: boolean
  url?: boolean
  label?: boolean
  description?: boolean
  tags?: boolean
  createdAt?: boolean
}, ExtArgs["result"]["sectionImage"]>

export type SectionImageSelectCreateManyAndReturn<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = runtime.Types.Extensions.GetSelect<{
  id?: boolean
  url?: boolean
  label?: boolean
  description?: boolean
  tags?: boolean
  createdAt?: boolean
}, ExtArgs["result"]["sectionImage"]>

export type SectionImageSelectUpdateManyAndReturn<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = runtime.Types.Extensions.GetSelect<{
  id?: boolean
  url?: boolean
  label?: boolean
  description?: boolean
  tags?: boolean
  createdAt?: boolean
}, ExtArgs["result"]["sectionImage"]>

export type SectionImageSelectScalar = {
  id?: boolean
  url?: boolean
  label?: boolean
  description?: boolean
  tags?: boolean
  createdAt?: boolean
}

export type SectionImageOmit<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = runtime.Types.Extensions.GetOmit<"id" | "url" | "label" | "description" | "tags" | "createdAt", ExtArgs["result"]["sectionImage"]>

export type $SectionImagePayload<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  name: "SectionImage"
  objects: {}
  scalars: runtime.Types.Extensions.GetPayloadResult<{
    id: string
    url: string
    label: string
    description: string | null
    tags: string[]
    createdAt: Date
  }, ExtArgs["result"]["sectionImage"]>
  composites: {}
}

export type SectionImageGetPayload<S extends boolean | null | undefined | SectionImageDefaultArgs> = runtime.Types.Result.GetResult<Prisma.$SectionImagePayload, S>

export type SectionImageCountArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> =
  Omit<SectionImageFindManyArgs, 'select' | 'include' | 'distinct' | 'omit'> & {
    select?: SectionImageCountAggregateInputType | true
  }

export interface SectionImageDelegate<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs, GlobalOmitOptions = {}> {
  [K: symbol]: { types: Prisma.TypeMap<ExtArgs>['model']['SectionImage'], meta: { name: 'SectionImage' } }
  /**
   * Find zero or one SectionImage that matches the filter.
   * @param {SectionImageFindUniqueArgs} args - Arguments to find a SectionImage
   * @example
   * // Get one SectionImage
   * const sectionImage = await prisma.sectionImage.findUnique({
   *   where: {
   *     // ... provide filter here
   *   }
   * })
   */
  findUnique<T extends SectionImageFindUniqueArgs>(args: Prisma.SelectSubset<T, SectionImageFindUniqueArgs<ExtArgs>>): Prisma.Prisma__SectionImageClient<runtime.Types.Result.GetResult<Prisma.$SectionImagePayload<ExtArgs>, T, "findUnique", GlobalOmitOptions> | null, null, ExtArgs, GlobalOmitOptions>

  /**
   * Find one SectionImage that matches the filter or throw an error with `error.code='P2025'`
   * if no matches were found.
   * @param {SectionImageFindUniqueOrThrowArgs} args - Arguments to find a SectionImage
   * @example
   * // Get one SectionImage
   * const sectionImage = await prisma.sectionImage.findUniqueOrThrow({
   *   where: {
   *     // ... provide filter here
   *   }
   * })
   */
  findUniqueOrThrow<T extends SectionImageFindUniqueOrThrowArgs>(args: Prisma.SelectSubset<T, SectionImageFindUniqueOrThrowArgs<ExtArgs>>): Prisma.Prisma__SectionImageClient<runtime.Types.Result.GetResult<Prisma.$SectionImagePayload<ExtArgs>, T, "findUniqueOrThrow", GlobalOmitOptions>, never, ExtArgs, GlobalOmitOptions>

  /**
   * Find the first SectionImage that matches the filter.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {SectionImageFindFirstArgs} args - Arguments to find a SectionImage
   * @example
   * // Get one SectionImage
   * const sectionImage = await prisma.sectionImage.findFirst({
   *   where: {
   *     // ... provide filter here
   *   }
   * })
   */
  findFirst<T extends SectionImageFindFirstArgs>(args?: Prisma.SelectSubset<T, SectionImageFindFirstArgs<ExtArgs>>): Prisma.Prisma__SectionImageClient<runtime.Types.Result.GetResult<Prisma.$SectionImagePayload<ExtArgs>, T, "findFirst", GlobalOmitOptions> | null, null, ExtArgs, GlobalOmitOptions>

  /**
   * Find the first SectionImage that matches the filter or
   * throw `PrismaKnownClientError` with `P2025` code if no matches were found.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {SectionImageFindFirstOrThrowArgs} args - Arguments to find a SectionImage
   * @example
   * // Get one SectionImage
   * const sectionImage = await prisma.sectionImage.findFirstOrThrow({
   *   where: {
   *     // ... provide filter here
   *   }
   * })
   */
  findFirstOrThrow<T extends SectionImageFindFirstOrThrowArgs>(args?: Prisma.SelectSubset<T, SectionImageFindFirstOrThrowArgs<ExtArgs>>): Prisma.Prisma__SectionImageClient<runtime.Types.Result.GetResult<Prisma.$SectionImagePayload<ExtArgs>, T, "findFirstOrThrow", GlobalOmitOptions>, never, ExtArgs, GlobalOmitOptions>

  /**
   * Find zero or more SectionImages that matches the filter.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {SectionImageFindManyArgs} args - Arguments to filter and select certain fields only.
   * @example
   * // Get all SectionImages
   * const sectionImages = await prisma.sectionImage.findMany()
   * 
   * // Get first 10 SectionImages
   * const sectionImages = await prisma.sectionImage.findMany({ take: 10 })
   * 
   * // Only select the `id`
   * const sectionImageWithIdOnly = await prisma.sectionImage.findMany({ select: { id: true } })
   * 
   */
  findMany<T extends SectionImageFindManyArgs>(args?: Prisma.SelectSubset<T, SectionImageFindManyArgs<ExtArgs>>): Prisma.PrismaPromise<runtime.Types.Result.GetResult<Prisma.$SectionImagePayload<ExtArgs>, T, "findMany", GlobalOmitOptions>>

  /**
   * Create a SectionImage.
   * @param {SectionImageCreateArgs} args - Arguments to create a SectionImage.
   * @example
   * // Create one SectionImage
   * const SectionImage = await prisma.sectionImage.create({
   *   data: {
   *     // ... data to create a SectionImage
   *   }
   * })
   * 
   */
  create<T extends SectionImageCreateArgs>(args: Prisma.SelectSubset<T, SectionImageCreateArgs<ExtArgs>>): Prisma.Prisma__SectionImageClient<runtime.Types.Result.GetResult<Prisma.$SectionImagePayload<ExtArgs>, T, "create", GlobalOmitOptions>, never, ExtArgs, GlobalOmitOptions>

  /**
   * Create many SectionImages.
   * @param {SectionImageCreateManyArgs} args - Arguments to create many SectionImages.
   * @example
   * // Create many SectionImages
   * const sectionImage = await prisma.sectionImage.createMany({
   *   data: [
   *     // ... provide data here
   *   ]
   * })
   *     
   */
  createMany<T extends SectionImageCreateManyArgs>(args?: Prisma.SelectSubset<T, SectionImageCreateManyArgs<ExtArgs>>): Prisma.PrismaPromise<Prisma.BatchPayload>

  /**
   * Create many SectionImages and returns the data saved in the database.
   * @param {SectionImageCreateManyAndReturnArgs} args - Arguments to create many SectionImages.
   * @example
   * // Create many SectionImages
   * const sectionImage = await prisma.sectionImage.createManyAndReturn({
   *   data: [
   *     // ... provide data here
   *   ]
   * })
   * 
   * // Create many SectionImages and only return the `id`
   * const sectionImageWithIdOnly = await prisma.sectionImage.createManyAndReturn({
   *   select: { id: true },
   *   data: [
   *     // ... provide data here
   *   ]
   * })
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * 
   */
  createManyAndReturn<T extends SectionImageCreateManyAndReturnArgs>(args?: Prisma.SelectSubset<T, SectionImageCreateManyAndReturnArgs<ExtArgs>>): Prisma.PrismaPromise<runtime.Types.Result.GetResult<Prisma.$SectionImagePayload<ExtArgs>, T, "createManyAndReturn", GlobalOmitOptions>>

  /**
   * Delete a SectionImage.
   * @param {SectionImageDeleteArgs} args - Arguments to delete one SectionImage.
   * @example
   * // Delete one SectionImage
   * const SectionImage = await prisma.sectionImage.delete({
   *   where: {
   *     // ... filter to delete one SectionImage
   *   }
   * })
   * 
   */
  delete<T extends SectionImageDeleteArgs>(args: Prisma.SelectSubset<T, SectionImageDeleteArgs<ExtArgs>>): Prisma.Prisma__SectionImageClient<runtime.Types.Result.GetResult<Prisma.$SectionImagePayload<ExtArgs>, T, "delete", GlobalOmitOptions>, never, ExtArgs, GlobalOmitOptions>

  /**
   * Update one SectionImage.
   * @param {SectionImageUpdateArgs} args - Arguments to update one SectionImage.
   * @example
   * // Update one SectionImage
   * const sectionImage = await prisma.sectionImage.update({
   *   where: {
   *     // ... provide filter here
   *   },
   *   data: {
   *     // ... provide data here
   *   }
   * })
   * 
   */
  update<T extends SectionImageUpdateArgs>(args: Prisma.SelectSubset<T, SectionImageUpdateArgs<ExtArgs>>): Prisma.Prisma__SectionImageClient<runtime.Types.Result.GetResult<Prisma.$SectionImagePayload<ExtArgs>, T, "update", GlobalOmitOptions>, never, ExtArgs, GlobalOmitOptions>

  /**
   * Delete zero or more SectionImages.
   * @param {SectionImageDeleteManyArgs} args - Arguments to filter SectionImages to delete.
   * @example
   * // Delete a few SectionImages
   * const { count } = await prisma.sectionImage.deleteMany({
   *   where: {
   *     // ... provide filter here
   *   }
   * })
   * 
   */
  deleteMany<T extends SectionImageDeleteManyArgs>(args?: Prisma.SelectSubset<T, SectionImageDeleteManyArgs<ExtArgs>>): Prisma.PrismaPromise<Prisma.BatchPayload>

  /**
   * Update zero or more SectionImages.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {SectionImageUpdateManyArgs} args - Arguments to update one or more rows.
   * @example
   * // Update many SectionImages
   * const sectionImage = await prisma.sectionImage.updateMany({
   *   where: {
   *     // ... provide filter here
   *   },
   *   data: {
   *     // ... provide data here
   *   }
   * })
   * 
   */
  updateMany<T extends SectionImageUpdateManyArgs>(args: Prisma.SelectSubset<T, SectionImageUpdateManyArgs<ExtArgs>>): Prisma.PrismaPromise<Prisma.BatchPayload>

  /**
   * Update zero or more SectionImages and returns the data updated in the database.
   * @param {SectionImageUpdateManyAndReturnArgs} args - Arguments to update many SectionImages.
   * @example
   * // Update many SectionImages
   * const sectionImage = await prisma.sectionImage.updateManyAndReturn({
   *   where: {
   *     // ... provide filter here
   *   },
   *   data: [
   *     // ... provide data here
   *   ]
   * })
   * 
   * // Update zero or more SectionImages and only return the `id`
   * const sectionImageWithIdOnly = await prisma.sectionImage.updateManyAndReturn({
   *   select: { id: true },
   *   where: {
   *     // ... provide filter here
   *   },
   *   data: [
   *     // ... provide data here
   *   ]
   * })
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * 
   */
  updateManyAndReturn<T extends SectionImageUpdateManyAndReturnArgs>(args: Prisma.SelectSubset<T, SectionImageUpdateManyAndReturnArgs<ExtArgs>>): Prisma.PrismaPromise<runtime.Types.Result.GetResult<Prisma.$SectionImagePayload<ExtArgs>, T, "updateManyAndReturn", GlobalOmitOptions>>

  /**
   * Create or update one SectionImage.
   * @param {SectionImageUpsertArgs} args - Arguments to update or create a SectionImage.
   * @example
   * // Update or create a SectionImage
   * const sectionImage = await prisma.sectionImage.upsert({
   *   create: {
   *     // ... data to create a SectionImage
   *   },
   *   update: {
   *     // ... in case it already exists, update
   *   },
   *   where: {
   *     // ... the filter for the SectionImage we want to update
   *   }
   * })
   */
  upsert<T extends SectionImageUpsertArgs>(args: Prisma.SelectSubset<T, SectionImageUpsertArgs<ExtArgs>>): Prisma.Prisma__SectionImageClient<runtime.Types.Result.GetResult<Prisma.$SectionImagePayload<ExtArgs>, T, "upsert", GlobalOmitOptions>, never, ExtArgs, GlobalOmitOptions>


  /**
   * Count the number of SectionImages.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {SectionImageCountArgs} args - Arguments to filter SectionImages to count.
   * @example
   * // Count the number of SectionImages
   * const count = await prisma.sectionImage.count({
   *   where: {
   *     // ... the filter for the SectionImages we want to count
   *   }
   * })
  **/
  count<T extends SectionImageCountArgs>(
    args?: Prisma.Subset<T, SectionImageCountArgs>,
  ): Prisma.PrismaPromise<
    T extends runtime.Types.Utils.Record<'select', any>
      ? T['select'] extends true
        ? number
        : Prisma.GetScalarType<T['select'], SectionImageCountAggregateOutputType>
      : number
  >

  /**
   * Allows you to perform aggregations operations on a SectionImage.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {SectionImageAggregateArgs} args - Select which aggregations you would like to apply and on what fields.
   * @example
   * // Ordered by age ascending
   * // Where email contains prisma.io
   * // Limited to the 10 users
   * const aggregations = await prisma.user.aggregate({
   *   _avg: {
   *     age: true,
   *   },
   *   where: {
   *     email: {
   *       contains: "prisma.io",
   *     },
   *   },
   *   orderBy: {
   *     age: "asc",
   *   },
   *   take: 10,
   * })
  **/
  aggregate<T extends SectionImageAggregateArgs>(args: Prisma.Subset<T, SectionImageAggregateArgs>): Prisma.PrismaPromise<GetSectionImageAggregateType<T>>

  /**
   * Group by SectionImage.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {SectionImageGroupByArgs} args - Group by arguments.
   * @example
   * // Group by city, order by createdAt, get count
   * const result = await prisma.user.groupBy({
   *   by: ['city', 'createdAt'],
   *   orderBy: {
   *     createdAt: true
   *   },
   *   _count: {
   *     _all: true
   *   },
   * })
   * 
  **/
  groupBy<
    T extends SectionImageGroupByArgs,
    HasSelectOrTake extends Prisma.Or<
      Prisma.Extends<'skip', Prisma.Keys<T>>,
      Prisma.Extends<'take', Prisma.Keys<T>>
    >,
    OrderByArg extends Prisma.True extends HasSelectOrTake
      ? { orderBy: SectionImageGroupByArgs['orderBy'] }
      : { orderBy?: SectionImageGroupByArgs['orderBy'] },
    OrderFields extends Prisma.ExcludeUnderscoreKeys<Prisma.Keys<Prisma.MaybeTupleToUnion<T['orderBy']>>>,
    ByFields extends Prisma.MaybeTupleToUnion<T['by']>,
    ByValid extends Prisma.Has<ByFields, OrderFields>,
    HavingFields extends Prisma.GetHavingFields<T['having']>,
    HavingValid extends Prisma.Has<ByFields, HavingFields>,
    ByEmpty extends T['by'] extends never[] ? Prisma.True : Prisma.False,
    InputErrors extends ByEmpty extends Prisma.True
    ? `Error: "by" must not be empty.`
    : HavingValid extends Prisma.False
    ? {
        [P in HavingFields]: P extends ByFields
          ? never
          : P extends string
          ? `Error: Field "${P}" used in "having" needs to be provided in "by".`
          : [
              Error,
              'Field ',
              P,
              ` in "having" needs to be provided in "by"`,
            ]
      }[HavingFields]
    : 'take' extends Prisma.Keys<T>
    ? 'orderBy' extends Prisma.Keys<T>
      ? ByValid extends Prisma.True
        ? {}
        : {
            [P in OrderFields]: P extends ByFields
              ? never
              : `Error: Field "${P}" in "orderBy" needs to be provided in "by"`
          }[OrderFields]
      : 'Error: If you provide "take", you also need to provide "orderBy"'
    : 'skip' extends Prisma.Keys<T>
    ? 'orderBy' extends Prisma.Keys<T>
      ? ByValid extends Prisma.True
        ? {}
        : {
            [P in OrderFields]: P extends ByFields
              ? never
              : `Error: Field "${P}" in "orderBy" needs to be provided in "by"`
          }[OrderFields]
      : 'Error: If you provide "skip", you also need to provide "orderBy"'
    : ByValid extends Prisma.True
    ? {}
    : {
        [P in OrderFields]: P extends ByFields
          ? never
          : `Error: Field "${P}" in "orderBy" needs to be provided in "by"`
      }[OrderFields]
  >(args: Prisma.SubsetIntersection<T, SectionImageGroupByArgs, OrderByArg> & InputErrors): {} extends InputErrors ? GetSectionImageGroupByPayload<T> : Prisma.PrismaPromise<InputErrors>
/**
 * Fields of the SectionImage model
 */
readonly fields: SectionImageFieldRefs;
}

/**
 * The delegate class that acts as a "Promise-like" for SectionImage.
 * Why is this prefixed with `Prisma__`?
 * Because we want to prevent naming conflicts as mentioned in
 * https://github.com/prisma/prisma-client-js/issues/707
 */
export interface Prisma__SectionImageClient<T, Null = never, ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs, GlobalOmitOptions = {}> extends Prisma.PrismaPromise<T> {
  readonly [Symbol.toStringTag]: "PrismaPromise"
  /**
   * Attaches callbacks for the resolution and/or rejection of the Promise.
   * @param onfulfilled The callback to execute when the Promise is resolved.
   * @param onrejected The callback to execute when the Promise is rejected.
   * @returns A Promise for the completion of which ever callback is executed.
   */
  then<TResult1 = T, TResult2 = never>(onfulfilled?: ((value: T) => TResult1 | PromiseLike<TResult1>) | undefined | null, onrejected?: ((reason: any) => TResult2 | PromiseLike<TResult2>) | undefined | null): runtime.Types.Utils.JsPromise<TResult1 | TResult2>
  /**
   * Attaches a callback for only the rejection of the Promise.
   * @param onrejected The callback to execute when the Promise is rejected.
   * @returns A Promise for the completion of the callback.
   */
  catch<TResult = never>(onrejected?: ((reason: any) => TResult | PromiseLike<TResult>) | undefined | null): runtime.Types.Utils.JsPromise<T | TResult>
  /**
   * Attaches a callback that is invoked when the Promise is settled (fulfilled or rejected). The
   * resolved value cannot be modified from the callback.
   * @param onfinally The callback to execute when the Promise is settled (fulfilled or rejected).
   * @returns A Promise for the completion of the callback.
   */
  finally(onfinally?: (() => void) | undefined | null): runtime.Types.Utils.JsPromise<T>
}




/**
 * Fields of the SectionImage model
 */
export interface SectionImageFieldRefs {
  readonly id: Prisma.FieldRef<"SectionImage", 'String'>
  readonly url: Prisma.FieldRef<"SectionImage", 'String'>
  readonly label: Prisma.FieldRef<"SectionImage", 'String'>
  readonly description: Prisma.FieldRef<"SectionImage", 'String'>
  readonly tags: Prisma.FieldRef<"SectionImage", 'String[]'>
  readonly createdAt: Prisma.FieldRef<"SectionImage", 'DateTime'>
}
    

// Custom InputTypes
/**
 * SectionImage findUnique
 */
export type SectionImageFindUniqueArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the SectionImage
   */
  select?: Prisma.SectionImageSelect<ExtArgs> | null
  /**
   * Omit specific fields from the SectionImage
   */
  omit?: Prisma.SectionImageOmit<ExtArgs> | null
  /**
   * Filter, which SectionImage to fetch.
   */
  where: Prisma.SectionImageWhereUniqueInput
}

/**
 * SectionImage findUniqueOrThrow
 */
export type SectionImageFindUniqueOrThrowArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the SectionImage
   */
  select?: Prisma.SectionImageSelect<ExtArgs> | null
  /**
   * Omit specific fields from the SectionImage
   */
  omit?: Prisma.SectionImageOmit<ExtArgs> | null
  /**
   * Filter, which SectionImage to fetch.
   */
  where: Prisma.SectionImageWhereUniqueInput
}

/**
 * SectionImage findFirst
 */
export type SectionImageFindFirstArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the SectionImage
   */
  select?: Prisma.SectionImageSelect<ExtArgs> | null
  /**
   * Omit specific fields from the SectionImage
   */
  omit?: Prisma.SectionImageOmit<ExtArgs> | null
  /**
   * Filter, which SectionImage to fetch.
   */
  where?: Prisma.SectionImageWhereInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/sorting Sorting Docs}
   * 
   * Determine the order of SectionImages to fetch.
   */
  orderBy?: Prisma.SectionImageOrderByWithRelationInput | Prisma.SectionImageOrderByWithRelationInput[]
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination#cursor-based-pagination Cursor Docs}
   * 
   * Sets the position for searching for SectionImages.
   */
  cursor?: Prisma.SectionImageWhereUniqueInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Take `±n` SectionImages from the position of the cursor.
   */
  take?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Skip the first `n` SectionImages.
   */
  skip?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/distinct Distinct Docs}
   * 
   * Filter by unique combinations of SectionImages.
   */
  distinct?: Prisma.SectionImageScalarFieldEnum | Prisma.SectionImageScalarFieldEnum[]
}

/**
 * SectionImage findFirstOrThrow
 */
export type SectionImageFindFirstOrThrowArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the SectionImage
   */
  select?: Prisma.SectionImageSelect<ExtArgs> | null
  /**
   * Omit specific fields from the SectionImage
   */
  omit?: Prisma.SectionImageOmit<ExtArgs> | null
  /**
   * Filter, which SectionImage to fetch.
   */
  where?: Prisma.SectionImageWhereInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/sorting Sorting Docs}
   * 
   * Determine the order of SectionImages to fetch.
   */
  orderBy?: Prisma.SectionImageOrderByWithRelationInput | Prisma.SectionImageOrderByWithRelationInput[]
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination#cursor-based-pagination Cursor Docs}
   * 
   * Sets the position for searching for SectionImages.
   */
  cursor?: Prisma.SectionImageWhereUniqueInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Take `±n` SectionImages from the position of the cursor.
   */
  take?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Skip the first `n` SectionImages.
   */
  skip?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/distinct Distinct Docs}
   * 
   * Filter by unique combinations of SectionImages.
   */
  distinct?: Prisma.SectionImageScalarFieldEnum | Prisma.SectionImageScalarFieldEnum[]
}

/**
 * SectionImage findMany
 */
export type SectionImageFindManyArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the SectionImage
   */
  select?: Prisma.SectionImageSelect<ExtArgs> | null
  /**
   * Omit specific fields from the SectionImage
   */
  omit?: Prisma.SectionImageOmit<ExtArgs> | null
  /**
   * Filter, which SectionImages to fetch.
   */
  where?: Prisma.SectionImageWhereInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/sorting Sorting Docs}
   * 
   * Determine the order of SectionImages to fetch.
   */
  orderBy?: Prisma.SectionImageOrderByWithRelationInput | Prisma.SectionImageOrderByWithRelationInput[]
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination#cursor-based-pagination Cursor Docs}
   * 
   * Sets the position for listing SectionImages.
   */
  cursor?: Prisma.SectionImageWhereUniqueInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Take `±n` SectionImages from the position of the cursor.
   */
  take?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Skip the first `n` SectionImages.
   */
  skip?: number
  distinct?: Prisma.SectionImageScalarFieldEnum | Prisma.SectionImageScalarFieldEnum[]
}

/**
 * SectionImage create
 */
export type SectionImageCreateArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the SectionImage
   */
  select?: Prisma.SectionImageSelect<ExtArgs> | null
  /**
   * Omit specific fields from the SectionImage
   */
  omit?: Prisma.SectionImageOmit<ExtArgs> | null
  /**
   * The data needed to create a SectionImage.
   */
  data: Prisma.XOR<Prisma.SectionImageCreateInput, Prisma.SectionImageUncheckedCreateInput>
}

/**
 * SectionImage createMany
 */
export type SectionImageCreateManyArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * The data used to create many SectionImages.
   */
  data: Prisma.SectionImageCreateManyInput | Prisma.SectionImageCreateManyInput[]
  skipDuplicates?: boolean
}

/**
 * SectionImage createManyAndReturn
 */
export type SectionImageCreateManyAndReturnArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the SectionImage
   */
  select?: Prisma.SectionImageSelectCreateManyAndReturn<ExtArgs> | null
  /**
   * Omit specific fields from the SectionImage
   */
  omit?: Prisma.SectionImageOmit<ExtArgs> | null
  /**
   * The data used to create many SectionImages.
   */
  data: Prisma.SectionImageCreateManyInput | Prisma.SectionImageCreateManyInput[]
  skipDuplicates?: boolean
}

/**
 * SectionImage update
 */
export type SectionImageUpdateArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the SectionImage
   */
  select?: Prisma.SectionImageSelect<ExtArgs> | null
  /**
   * Omit specific fields from the SectionImage
   */
  omit?: Prisma.SectionImageOmit<ExtArgs> | null
  /**
   * The data needed to update a SectionImage.
   */
  data: Prisma.XOR<Prisma.SectionImageUpdateInput, Prisma.SectionImageUncheckedUpdateInput>
  /**
   * Choose, which SectionImage to update.
   */
  where: Prisma.SectionImageWhereUniqueInput
}

/**
 * SectionImage updateMany
 */
export type SectionImageUpdateManyArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * The data used to update SectionImages.
   */
  data: Prisma.XOR<Prisma.SectionImageUpdateManyMutationInput, Prisma.SectionImageUncheckedUpdateManyInput>
  /**
   * Filter which SectionImages to update
   */
  where?: Prisma.SectionImageWhereInput
  /**
   * Limit how many SectionImages to update.
   */
  limit?: number
}

/**
 * SectionImage updateManyAndReturn
 */
export type SectionImageUpdateManyAndReturnArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the SectionImage
   */
  select?: Prisma.SectionImageSelectUpdateManyAndReturn<ExtArgs> | null
  /**
   * Omit specific fields from the SectionImage
   */
  omit?: Prisma.SectionImageOmit<ExtArgs> | null
  /**
   * The data used to update SectionImages.
   */
  data: Prisma.XOR<Prisma.SectionImageUpdateManyMutationInput, Prisma.SectionImageUncheckedUpdateManyInput>
  /**
   * Filter which SectionImages to update
   */
  where?: Prisma.SectionImageWhereInput
  /**
   * Limit how many SectionImages to update.
   */
  limit?: number
}

/**
 * SectionImage upsert
 */
export type SectionImageUpsertArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the SectionImage
   */
  select?: Prisma.SectionImageSelect<ExtArgs> | null
  /**
   * Omit specific fields from the SectionImage
   */
  omit?: Prisma.SectionImageOmit<ExtArgs> | null
  /**
   * The filter to search for the SectionImage to update in case it exists.
   */
  where: Prisma.SectionImageWhereUniqueInput
  /**
   * In case the SectionImage found by the `where` argument doesn't exist, create a new SectionImage with this data.
   */
  create: Prisma.XOR<Prisma.SectionImageCreateInput, Prisma.SectionImageUncheckedCreateInput>
  /**
   * In case the SectionImage was found with the provided `where` argument, update it with this data.
   */
  update: Prisma.XOR<Prisma.SectionImageUpdateInput, Prisma.SectionImageUncheckedUpdateInput>
}

/**
 * SectionImage delete
 */
export type SectionImageDeleteArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the SectionImage
   */
  select?: Prisma.SectionImageSelect<ExtArgs> | null
  /**
   * Omit specific fields from the SectionImage
   */
  omit?: Prisma.SectionImageOmit<ExtArgs> | null
  /**
   * Filter which SectionImage to delete.
   */
  where: Prisma.SectionImageWhereUniqueInput
}

/**
 * SectionImage deleteMany
 */
export type SectionImageDeleteManyArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Filter which SectionImages to delete
   */
  where?: Prisma.SectionImageWhereInput
  /**
   * Limit how many SectionImages to delete.
   */
  limit?: number
}

/**
 * SectionImage without action
 */
export type SectionImageDefaultArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the SectionImage
   */
  select?: Prisma.SectionImageSelect<ExtArgs> | null
  /**
   * Omit specific fields from the SectionImage
   */
  omit?: Prisma.SectionImageOmit<ExtArgs> | null
}
